gripper_actuator:
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 232
  CCW_Angle_Limit: 650
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 80
  Goal_Position: 650

gripper_z_rot:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 471
  CCW_Angle_Limit: 1023
  CW_Compliance_Slope: 62
  CCW_Compliance_Slope: 62
  Moving_Speed: 150
  Goal_Position: 748
  # Goal_Position: 761

wrist_y_rot:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 180
  CCW_Angle_Limit: 836
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 80
  Goal_Position: 520
  # Goal_Position: 757

elbow_y_rot:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 180
  CCW_Angle_Limit: 835
  CW_Compliance_Slope: 32
  CCW_Compliance_Slope: 32
  Moving_Speed: 30
  Goal_Position: 389
  # Goal_Position: 467

base_y_rot:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 320
  CCW_Angle_Limit: 800
  CW_Compliance_Slope: 32
  CCW_Compliance_Slope: 32
  Moving_Speed: 30
  Goal_Position: 515
  # Goal_Position: 448

base_z_rot:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 80
  Goal_Position: 506
  # Goal_Position: 487